### ISSUE TITLE
numero de plot

### ISSUE THREAD

**Issue by reyzaguirre** [CIP-RIU/hidap_issues#49]
En el augmented design, el número de plot se reinicia en cada bloque. En el ejemplo:
- el primer bloque va de 1 a 29.
- el segundo bloque en lugar de empezar en 30, empieza en 11.
- el tercer bloque en lugar de empezar en 59, empieza en 21,
- etc.
[SPAgronomic052017_CHIARA_exp1.xlsx](https://github.com/omarbenites/hidap_issues/files/974482/SPAgronomic052017_CHIARA_exp1.xlsx)

**Comment by reyzaguirre** [comment]
Lo mismo con el RCBD
El primer bloque empieza en 1, el segundo en 11, el tercero en 21, etc

**Comment by reyzaguirre** [comment]
Sospecho que esto ocurre en todos los diseños, salvo el split plot que hemos personalizado.
Yo soy de los que prefiere ver en el número de plot un simple correlativo que empieza en 1 y va hasta donde tiene que ir.

**Comment by omarbenites** [comment]
El problema en si es del agricolae. En R, corrí el diseno de bloques completos al azar (abajo el código) y me sale este output
p <- letters[1:22]
fb <- design.rcbd(p,5,serie = 1)
fb$book

![image](https://cloud.githubusercontent.com/assets/5264796/25681277/5c3f456a-3019-11e7-8351-e095535c2f61.png)

En cada bloque, se genera una nueva numeración.

**Comment by reyzaguirre** [comment]
Así es, ese es el estilo de agricolae.

**Comment by reyzaguirre** [comment]
Propongo eliminar este estilo de agricolae

**Comment by reyzaguirre** [comment]
Comentario adicional del training de Africa: Soy de la idea que este label series de agricolae no aporta. A algunos participantes les ha creado confusión. Lo que sí es importante es darle un número de posición a cada parcela en cuanto a fila y columna. Esto está implementado en SPBase.

**Comment by cipriuhq** [comment]
Relacionado al issue #112. Label series acaba de ser retirado.
