### ISSUE TITLE
Histogram for Late Blight (AUDPC)

### ISSUE THREAD

**Issue by omarbenites** [CIP-RIU/hidap_issues#54]
Module: Single Analysis (tentative)
Description: The AUDPC requieres a descriptive statistical report that can also might be applied for other traits or variables. This report should incorporate the following content,

- [ ] Web user interface
- [ ] Scheme of the AUDPC (among other traits) report.
- [ ] Descriptive statistics: min, max, std, etc.
- [ ] Histogram graphics (publication style).
- [ ] Customization of graphics using buttons.
- [ ] Discuss with Raul about statistical details.

**Comment by cipriuhq** [comment]
Now related to [eda4plant](https://github.com/CIP-RIU/eda4plant )
This new repo contains graph module.
