### ISSUE TITLE
Valores atipicos y valores fuera de rango.

### ISSUE THREAD

**Issue by reyzaguirre** [CIP-RIU/hidap_issues#59]
Para la detección de valores fuera de rango (los que se pintan en rojo en el fieldbook check) propondría las siguientes reglas:

1.	Variables que toman un numero finito de valores, por ejemplo 1, 3, 5, 7, 9. Cualquier valor fuera de los listados debe ser pintado en rojo. Actualmente puedo ingresar 50.5 plantas y no lo pinta de rojo.
![screenshot 2017-05-08 16 01 56](https://cloud.githubusercontent.com/assets/7216359/25825305/2db582c0-3408-11e7-9aea-f1119136c4ae.png)

2.	Variables que toman infinitos valores dentro de un rango, por ejemplo materia seca, 0-100. Cualquier valor menor a 0 o mayor a 100 debe ser pintado de rojo.
3.	Variables que toman valores en los reales positivos, por ejemplo rendimiento. Solo pintar de rojo valores negativos. No le encuentro sentido a ponerle un tope superior a variables como rendimiento, pues este depende del número de plantas y en cualquier caso sería un límite subjetivo.

**Comment by reyzaguirre** [comment]
Durante el entrenamiento en África caí en la cuenta de que, para camote al menos, si bien la escala subjetiva para evaluaciones tiene descripciones para 1, 3, 5, 7, y 9, los valores intermedios 2, 4, 6 y 8 también son válidos.

**Comment by omarbenites** [comment]
Lo he modificado. En la próxima versión se verán los cambios. :sweet_potato:
