### ISSUE TITLE
PVS/Check fieldbook

### ISSUE THREAD

**Issue by STOALM** [CIP-RIU/hidap_issues#78]
Sel_Criteria:
1) Should follow the same pattern as the rest of criteria. "Resistant" instead of "Resistance"
![image](https://cloud.githubusercontent.com/assets/25850965/26250864/10d11df6-3c71-11e7-8c0c-30aada985102.png)
2)
weevil and flores should be in lower case 
![image](https://cloud.githubusercontent.com/assets/25850965/26250963/60bdb0cc-3c71-11e7-8306-6005d60bdd39.png)
3)
Bright-green
![image](https://cloud.githubusercontent.com/assets/25850965/26251082/b6a6d8e2-3c71-11e7-9297-6a779f019bec.png)
Light-green
![image](https://cloud.githubusercontent.com/assets/25850965/26251099/c5174682-3c71-11e7-9c83-38d5ba2b2972.png)
4)
skin in low case
![image](https://cloud.githubusercontent.com/assets/25850965/26251426/d5eb0b96-3c72-11e7-87bc-8fd3bc72423a.png)
5)
oblong in low case
![image](https://cloud.githubusercontent.com/assets/25850965/26251444/e2a4b760-3c72-11e7-886f-b233fa7954b5.png)
6)
Delete one, doble
![image](https://cloud.githubusercontent.com/assets/25850965/26251501/1192823c-3c73-11e7-90ea-e70577a07ead.png)
7)
cooking in low case
![image](https://cloud.githubusercontent.com/assets/25850965/26251517/252ddabc-3c73-11e7-88ed-45d0720c022d.png)
8)
shape and late in low case
![image](https://cloud.githubusercontent.com/assets/25850965/26251545/3a9357ce-3c73-11e7-90fe-8df91426be9a.png)
9)
Delete the one in spanglish
![image](https://cloud.githubusercontent.com/assets/25850965/26251588/5f9043e8-3c73-11e7-8228-7fa5e571f9ab.png)
10)
weevil and size in low case
![image](https://cloud.githubusercontent.com/assets/25850965/26251605/73fa64ee-3c73-11e7-8c7c-e916e0464146.png)
11)
Criteria instead of criterias
![image](https://cloud.githubusercontent.com/assets/25850965/26252243/54d4cbc0-3c75-11e7-9e32-7e054cf3b968.png)
![image](https://cloud.githubusercontent.com/assets/25850965/26252080/e2ec7c38-3c74-11e7-96fe-78545ce0776f.png)
12)
F7 is: Organoleptic_baby
![image](https://cloud.githubusercontent.com/assets/25850965/26252034/bcb34d6c-3c74-11e7-95c3-0b9d8ef00729.png)

**Comment by STOALM** [comment]
11)
Criteria instead of criterias
![image](https://cloud.githubusercontent.com/assets/25850965/26252243/54d4cbc0-3c75-11e7-9e32-7e054cf3b968.png)
![image](https://cloud.githubusercontent.com/assets/25850965/26252080/e2ec7c38-3c74-11e7-96fe-78545ce0776f.png)
12)
F7 is: Organoleptic_baby
![image](https://cloud.githubusercontent.com/assets/25850965/26252034/bcb34d6c-3c74-11e7-95c3-0b9d8ef00729.png)

**Comment by cipriuhq** [comment]
Now solved.
