### ISSUE TITLE
Wescott design

### ISSUE THREAD

**Issue by reyzaguirre** [CIP-RIU/hidap_issues#83]
Seria un golazo tenerlo ya mismo

**Comment by omarbenites** [comment]
Implementado con la ultima actualización. :sweet_potato: 
Aqui un ejemplito.

Material List para westcott design
:notebook: 
[Material_List_westcott.xlsx](https://github.com/CIP-RIU/hidap_issues/files/1102757/Material_List_westcott.xlsx)

Fieldbook creado por HiDAP
:book: 
[PTDrought062017_BEMBEK.xlsx](https://github.com/CIP-RIU/hidap_issues/files/1102744/PTDrought062017_BEMBEK.xlsx)
