### ISSUE TITLE
New list - type of procedure

### ISSUE THREAD

**Issue by reyzaguirre** [CIP-RIU/hidap_issues#87]
¿Cuál es la utilidad del "Type of procedure"? Si no tiene utilidad clara habría que sacarlo.

![screenshot 2017-06-20 14 21 25](https://user-images.githubusercontent.com/7216359/27351774-1285a3b2-55c4-11e7-8cd8-4ee6564f400a.png)

**Comment by omarbenites** [comment]
Esto sirve para crear listas de materiales con los experimentos standard y listas con columnas diferentes para el diseño de mamá y bebe. Esto se debe aclarar en el manual de HiDAP.

**Comment by reyzaguirre** [comment]
¿Cual es para experimentos y cual para mama y bebe? Ojo que ambos son para seleccionar variedades.
Propongo cambiar las etiquetas a:
- Field experiment.
- PVS

**Comment by omarbenites** [comment]
Con Standard hacia referencia a los experimentos que normalmente se usan (yield, late blight, etc) y Varietal Selection a PVS. Voy las etiquetas para que quede mas claro.

**Comment by omarbenites** [comment]
Acaba de ser cambiado a Standard y PVS en el combo de seleccion.
