### ISSUE TITLE
La lista se exporta sin extension xlsx

### ISSUE THREAD

**Issue by reyzaguirre** [CIP-RIU/hidap_issues#88]
Cuando se exporta la lista se han olvidado de ponerle la extension xlsx al archivo.

![screenshot 2017-06-20 14 26 17](https://user-images.githubusercontent.com/7216359/27352021-e427984e-55c4-11e7-82c8-8bdacd0fe5f9.png)

 Al menos en mi PC se graba sin extensión.

![screenshot 2017-06-20 14 28 36](https://user-images.githubusercontent.com/7216359/27352023-eac1ddfe-55c4-11e7-9b17-db11d8b0ab93.png)

**Comment by omarbenites** [comment]
Ahora arreglado. :+1:
