### ISSUE TITLE
Orden de los diseños

### ISSUE THREAD

**Issue by reyzaguirre** [CIP-RIU/hidap_issues#89]
Sugeriría un orden alfabético para los diseños.
![screenshot 2017-06-20 14 39 31](https://user-images.githubusercontent.com/7216359/27352438-5f75d410-55c6-11e7-9b77-1705352b2089.png)

**Comment by omarbenites** [comment]
?*Y si lo colocamos por orden de uso?. Primeros el dca, dbca, luego el aumentado, sin replicas, alfa, split plots, factoriales etc.

**Comment by reyzaguirre** [comment]
Yo prefiero el alfabetico, o sino por orden de complejidad:
- Unreplicated
- Unreplicated with checks (Wescott)
- CRD
- RCBD
- ABD
- A01
- Factorial with CRD
- Factorial with RCBD
- Split plot

**Comment by omarbenites** [comment]
Solucionado.
