### ISSUE TITLE
lugar de descarga para libros de campo

### ISSUE THREAD

**Issue by reyzaguirre** [CIP-RIU/hidap_issues#90]
Los libros de campo se siguen guardando (en el formato Excel) en 
C:\Users\eluser\AppData\Local\HIDAP\xdata\Default

Otros archivos como las listas de materiales se descargan en el folder especificado para descargas en el navegador. Creo que todo debiera descargarse en el mismo sitio.

**Comment by omarbenites** [comment]
Si por un problema de la libreria openxlsx, las rutas de los libros de campo cuando se crean y lo se exportan muestran inconvenientes. Mientras para labores sencillas como la lista de materiales no surge problema.
