### ISSUE TITLE
Special Modules

### ISSUE THREAD

**Issue by reyzaguirre** [CIP-RIU/hidap_issues#91]
Creo que en New fieldbook debería ir solo la opción de crear fieldbooks. Las dos pestañas de "Standard Modules" y "Special Modules" no me gustan. Lo de PVS lo pondría en otro lado, quizá en su propio menú a la izquierda. Estos no son experimentos de campo, son metodologías participativas.

![screenshot 2017-06-20 14 50 38](https://user-images.githubusercontent.com/7216359/27352903-e9b65ae0-55c7-11e7-9a72-9218675eb664.png)

En el lado izquierdo donde dice "PVS Trial Analysis" podría decir simplemente "PVS" y dentro poner dos opciones:
- Forms o Download forms.
- Analysis

**Comment by cipriuhq** [comment]
Por el momento se queda asi.
