### ISSUE TITLE
F2 & F3: PVS book won't generate reports

### ISSUE THREAD

**Issue by STOALM** [CIP-RIU/hidap_issues#94]
When generating the reports for F2 & F3, this error comes up:
![image](https://user-images.githubusercontent.com/25850965/27439431-8bfcabcc-572d-11e7-9a73-fad24220d4fb.png)

[PTPVS112016_COLPAR_exp1.xlsx](https://github.com/CIP-RIU/hidap_issues/files/1095115/PTPVS112016_COLPAR_exp1.xlsx)

[PTPVS112016_PMVL_exp1.xlsx](https://github.com/CIP-RIU/hidap_issues/files/1095464/PTPVS112016_PMVL_exp1.xlsx)

**Comment by reyzaguirre** [comment]
Es que no hay datos para bebe

**Comment by STOALM** [comment]
The fact that there is no data for baby, is not a problem for generating reports F2 & F3, I submit this example:
[PTPVS112016_YANA_exp1.xlsx](https://github.com/CIP-RIU/hidap_issues/files/1097783/PTPVS112016_YANA_exp1.xlsx)
[Best genotypes at flowering.docx](https://github.com/CIP-RIU/hidap_issues/files/1097785/Best.genotypes.at.flowering.docx)
[Best genotypes at harvest.docx](https://github.com/CIP-RIU/hidap_issues/files/1097786/Best.genotypes.at.harvest.docx)

**Comment by reyzaguirre** [comment]
The problem is in the Friedman test. To run this test you need all the judges testing all the genotypes (this is similar to a randomized COMPLETE block design). In this data set each judge tests only a subset.

**Comment by omarbenites** [comment]
Additionally, I have uploaded again these files with the highlighted genotypes  (in red) which do not have repetitions. 

[PTPVS112016_PMVL_exp1-Corregir.xlsx](https://github.com/CIP-RIU/hidap_issues/files/1099106/PTPVS112016_PMVL_exp1-Corregir.xlsx)
[PTPVS112016_COLPAR_exp1-Corregir.xlsx](https://github.com/CIP-RIU/hidap_issues/files/1099105/PTPVS112016_COLPAR_exp1-Corregir.xlsx)
