### ISSUE TITLE
problema con diseño aumentado

### ISSUE THREAD

**Issue by reyzaguirre** [CIP-RIU/hidap_issues#95]
[Material_List.xlsx](https://github.com/CIP-RIU/hidap_issues/files/1128536/Material_List.xlsx)
Cuando los checks van al final en la lista de materiales (ver adjunto), no se reconocen como checks en el diseño aumentado. Aparece el error:
![screenshot 2017-07-06 11 18 29](https://user-images.githubusercontent.com/7216359/27921785-7f257854-623e-11e7-8772-a090b8b983d7.png)

**Comment by omarbenites** [comment]
La cajita de azul , solamente es un aviso (advice), de que necesitas 2 checks al menos. El warning es otro mensaje que aparece cuando le das en Book Preview y no te va generar el libro.
Trata de crear el archivo y me indicas. Quedo atento a tu respuesta

**Comment by cipriuhq** [comment]
Encontre el error, se debia a la actualizacion de la libreria readxl y la inclusion de cellranger. Hay que probar en tu maquina.

**Comment by cipriuhq** [comment]
Agregar la ultima versión de HIDAP los siguientes paquetes actualizados:
- readxl
- cellranger
