### ISSUE TITLE
Duplication of variables SDW and SDW

### ISSUE THREAD

**Issue by omarbenites** [CIP-RIU/hidap_issues#97]
Exist two variables, **SDW** and **SDW**, which are repeated in the trait dictionary, both appear in drought and biochemical variables.

![image](https://user-images.githubusercontent.com/5264796/28342690-1b4aec9c-6bdf-11e7-94e6-f68f7ff40497.png)

![image](https://user-images.githubusercontent.com/5264796/28342703-2771c9f0-6bdf-11e7-9d80-0554e4746310.png)

The excel-online version is here:

https://github.com/CIP-RIU/RIU_docs/wiki/HIDAP-Trait-Dictionary

**Comment by cipriuhq** [comment]
@STOALM esto lo cierro?

**Comment by STOALM** [comment]
Yo creo que sí, porque ahora las variables de Drought van a ser diferentes y ya no aplicaría.

**Comment by omarbenites** [comment]
closed :sweet_potato:
